from __future__ import annotations

from app.models import Signal


class ScoringService:
    """Simple scoring service that turns technical signals into a ranked signal payload."""

    def score_signal(self, symbol: str, confidence: float, score: int) -> Signal:
        if score < 80:
            raise ValueError("score must be at least 80 to qualify")
        return Signal(
            symbol=symbol,
            action="BUY_CE",
            strike=0.0,
            expiry="weekly",
            entry_price=0.0,
            stop_loss=0.0,
            target_1=0.0,
            target_2=0.0,
            confidence=confidence,
            score=score,
            explanation="High-confidence momentum signal generated by the scoring engine.",
        )
