from pathlib import Path


def test_early_armed_entry_settings_are_present_in_env_files() -> None:
    root = Path(__file__).resolve().parent.parent
    required = {
        "ENABLE_EARLY_ARMED_ENTRY",
        "EARLY_ARMED_ENTRY_PAPER_ONLY",
        "EARLY_ARM_MIN_SCORE",
        "EARLY_ARM_TRIGGER_BUFFER_PCT",
        "EARLY_ARM_ALLOW_PREMIUM_PENDING",
        "ENABLE_TICK_QUALITY_CONFIRMATION",
        "TICK_QUALITY_MIN_TICKS_ABOVE_TRIGGER",
        "TICK_QUALITY_HOLD_SECONDS",
        "TICK_QUALITY_REQUIRE_BID_PROGRESS",
        "TICK_QUALITY_MAX_SPREAD_MULTIPLIER",
        "ENABLE_REJECTED_OUTCOME_CANDLE_REPLAY",
        "REJECTED_OUTCOME_REPLAY_TIMEFRAMES",
        "REJECTED_OUTCOME_REPLAY_MAX_CANDLES",
        "REJECTED_OUTCOME_USE_WS_TOKEN_CANDLES",
        "REJECTED_OUTCOME_AMBIGUOUS_CANDLE_POLICY",
        "REJECTED_OUTCOME_BATCH_LIMIT",
        "REJECTED_OUTCOME_MAX_BATCHES",
        "REJECTED_OUTCOME_BATCH_DELAY_SECONDS",
        "AUTOMATION_EXHAUST_REJECTED_OUTCOMES_AFTER_CLOSE",
        "ENABLE_TARGETED_OPTION_CANDLE_BACKFILL",
        "TARGETED_OPTION_CANDLE_BACKFILL_TIMEFRAMES",
        "TARGETED_OPTION_CANDLE_BACKFILL_BATCH_LIMIT",
        "TARGETED_OPTION_CANDLE_BACKFILL_MAX_CONTRACTS",
        "TARGETED_OPTION_CANDLE_BACKFILL_DELAY_SECONDS",
        "MIN_TARGETED_OPTION_CANDLE_COVERAGE_PCT",
        "ENABLE_LIVE_OPTION_CANDLE_GAP_BACKFILL",
        "LIVE_OPTION_CANDLE_BACKFILL_TIMEFRAMES",
        "LIVE_OPTION_CANDLE_BACKFILL_LOOKBACK_MINUTES",
        "LIVE_OPTION_CANDLE_BACKFILL_INTERVAL_SECONDS",
        "LIVE_OPTION_CANDLE_BACKFILL_MIN_GAP_SECONDS",
        "LIVE_OPTION_CANDLE_BACKFILL_MAX_CONTRACTS",
        "LIVE_OPTION_CANDLE_BACKFILL_BATCH_LIMIT",
        "LIVE_OPTION_CANDLE_BACKFILL_DELAY_SECONDS",
        "ENABLE_ON_DEMAND_PREMIUM_CANDLE_BACKFILL",
        "ON_DEMAND_PREMIUM_CANDLE_BACKFILL_COOLDOWN_SECONDS",
    }

    for filename in (".env", ".env.example"):
        text = root.joinpath(filename).read_text()
        missing = [key for key in required if f"{key}=" not in text]
        assert missing == []
